workflows:
  android-workflow:
    name: Flangapp PRO Android aab
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "apps.jobee.bg"
      flutter: 3.16.7
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build AAB with Flutter
        script: |
          cd . && flutter build appbundle --release --no-tree-shake-icons --build-name=1.0.26 --build-number=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      scripts:
        - name: HTTP notification
          script: |
            curl https://api.appifay.eu/public/observe/notice?uid=f6748fd1-0032-0cc1-f1d5-95d7bc4001c9