
class Config {

  /// Generated by Flangapp PRO 10-07-2024 16:18
  /// App UID: 588ac041-e246-d7d1-ade0-cede1ce41b95
  /// Version: 1.0.12
  /// API server: https://api.appifay.eu/

  /// *** Main settings *** ///
  static String apiUrl = "https://api.appifay.eu/";
  static String appUid = "588ac041-e246-d7d1-ade0-cede1ce41b95";
  static String oneSignalPushId = "";

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#F44336";
  // Text color (any HEX color)
  static String splashTextColor = "#ffffff";
  // Is image background
  static bool splashIsBackgroundImage = false;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "dsadsadsa";
  // Delay display (seconds)
  static int splashDelay = 3;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = true;

  /// *** Offline localization settings *** ///
  static String offlineErrorMessage = "Няма интернет връзка";
  static String offlineImage = "dino.png";

  /// *** Subscribe need settings *** ///
  static String subscribeErrorTitle = "App not available";
  static String subscribeErrorMessage = "This app may have been removed or your administrator may need to renew your subscription";
}